export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  REFRESH_CONFLICT: 'REFRESH_CONFLICT',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  NO_SITE: 'NO_SITE',
  LOW_ACCURACY: 'LOW_ACCURACY',
  OUTSIDE_SITE: 'OUTSIDE_SITE',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  ALREADY_CHECKED_OUT: 'ALREADY_CHECKED_OUT',
  NOT_CHECKED_IN: 'NOT_CHECKED_IN',
  PHONE_TAKEN: 'PHONE_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  EMPLOYEE_CODE_TAKEN: 'EMPLOYEE_CODE_TAKEN',
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  INVALID_CHECKOUT_TIME: 'INVALID_CHECKOUT_TIME',
  INVALID_STATE: 'INVALID_STATE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
